# Generated by Django 5.2.12 on 2026-03-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
